version: '3.9'

services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: "${DB_CONT_NAME}"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Stigmastigma1
    ports:
      - "${DB_PORT}:1433"
    volumes:
      - diary-log-data:/var/opt/mssql:rw

  web:
    build:
      context: "diary-log-angular"
    image: "localhost:7002/diary-log-angular"
    container_name: "${WEB_CONT_NAME}"
    ports:
      - "${WEB_PORT}:80"

  api:
    build:
      context: "DiaryLog"
    image: "localhost:7002/diary-log-api"
    container_name: "${API_CONT_NAME}"
    ports:
      - "${API_PORT}:80"
    depends_on:
      - "db"
    environment:
      - "DiaryLogConnectionString=Server=20.123.8.20,${DB_PORT};Database=DiaryLog;User Id=sa;Password=Stigmastigma1;"

volumes:
  diary-log-data: