version: '3.9'

services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: "${DB_CONT_NAME}"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Stigmastigma1
    ports:
      - "${DB_PORT}:1433"
    volumes:
      - diary-log-data:/var/opt/mssql:rw

  web:
    build:
      context: "diary-log-angular"
    image: "localhost:7002/diary-log-angular"
    container_name: "${WEB_CONT_NAME}"
    ports:
      - "${WEB_PORT}:80"

  api:
    build:
      context: "DiaryLog"
    image: "localhost:7002/diary-log-api"
    container_name: "${DB_CONT_NAME}"
    ports:
      - "${API_PORT}:80"
    depends_on:
      - "db"
    environment:
      - "DiaryLogConnectionString=Server=20.123.8.20,${DB_PORT};Database=DiaryLog;User Id=sa;Password=Stigmastigma1;"

  portainer:
    image: portainer/portainer-ce
    container_name: "portainer"
    ports:
      - "7001:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"

  docker-registry:
    image: "registry"
    volumes:
      - "registry_data:/var/lib/registry"
    ports:
      - "7002:5000"

  docker-registry-ui:
    image: "parabuzzle/craneoperator"
    ports:
      - "7003:80"
    environment:
      - REGISTRY_HOST=docker-registry
      - REGISTRY_PORT=5000
      - REGISTRY_PROTOCOL=http
      - SSL_VERIFY=false
      - USERNAME=admin
      - PASSWORD=password
    depends_on:
      - docker-registry

volumes:
  diary-log-data:
  portainer_data:
  registry_data: