// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DiaryLogApi.Models
{
    public partial class Category
    {
        public int Id { get; set; }
        public string CategoryName { get; set; }
    }
}