// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DiaryLogApi.Models
{
    public partial class Comment
    {
        public int? PostId { get; set; }
        public int? UserId { get; set; }
        public int Id { get; set; }
        public string Content { get; set; }

        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}