// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DiaryLogApi.Models
{
    public partial class PostCategory
    {
        public int? CategoryId { get; set; }
        public int? PostId { get; set; }

        public virtual Category Category { get; set; }
        public virtual Post Post { get; set; }
    }
}