// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace DiaryLogDomain;

public partial class Category
{
    public Category()
    {
        PostCategories = new HashSet<PostCategory>();
    }

    public int Id { get; set; }
    public int UserId { get; set; }
    public string CategoryName { get; set; } = null!;

    [JsonIgnore]
    public virtual User User { get; set; } = null!;
    [JsonIgnore]
    public virtual ICollection<PostCategory> PostCategories { get; set; }
}