// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DiaryLogDomain;

public partial class Post
{
    public Post()
    {
        Comments = new HashSet<Comment>();
        PostCategories = new HashSet<PostCategory>();
        Ratings = new HashSet<Rating>();
    }

    public int Id { get; set; }
    public int UserId { get; set; }
    public DateTime Date { get; set; }
    public string Title { get; set; } = null!;
    public string Content { get; set; } = null!;

    public virtual User User { get; set; } = null!;
    public virtual ICollection<Comment> Comments { get; set; }
    public virtual ICollection<PostCategory> PostCategories { get; set; }
    public virtual ICollection<Rating> Ratings { get; set; }
}