// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace DiaryLogDomain;

public partial class Rating
{
    public int UserId { get; set; }
    public int PostId { get; set; }
    public bool? IsLike { get; set; }

    public virtual Post Post { get; set; } = null!;
    public virtual User User { get; set; } = null!;
}